name: Rick Jarrell
description: Product Manager, Real Estate Investor
meta_description: Product Manager, Real Estate Investor

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: "http://www.rickjarrell.com"
google_analytics: "UA-118817479-3"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Rick Jarrell"

# Disqus config
disqus-shortname: ""
